git-lfs/build-dockers

centos_5.bootstrap
centos_5_test.dockerfile

This should disable cgo for the lfs docker gauntlet on centos 5. I think :)

disable cgo on centos 5

---

build_dockers.bsh
commit_tags.bsh

Besides it being a new version (and new is always better, especially in software), there's also a [security fix in it](https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4). :feelsgood:

bump go to 1.5.3

---

build_dockers.bsh

This pull-request teaches the `build_dockers.bsh` script to interact with the new directory structure introduced in e575ec73ced3d006e8b75641ac132931d55cde84.
I can break this change down into a few parts:
- Fix the `ls -d` glob to search for all of the `Dockerfile`s.
- Fix both `sed` invocations to produce a correct image name.
- Fix the `docker build` invocation to point at the correct directory.
--
/cc @technoweenie @rubyist @andyneff

build_dockers: new directory structure

---

centos_6.Dockerfile
centos_7.Dockerfile
centos_script.bsh
debian_script.bsh
test_lfs.bsh

This pull-request renames all uses of `github.com/github/git-lfs` to `github.com/git-lfs/git-lfs` to reflect the recent org change.
```bash
~/g/build-dockers (rename-org) $ ack "github\.com/github/git-lfs"
~/g/build-dockers (rename-org) $
```
---
/cc @andyneff @technoweenie

all: rename org from github to git-lfs

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
commit_tags.bsh

Previously, the version of LFS that we used to boostrap used the old naming
convention: 'github.com/github/git-lfs". The Dockerfiles in this repository
assume the latest naming convention "github.com/git-lfs/git-lfs".
This commit bumps the bootstrapped version to `release-1.5` so we can start
using the new naming conventions throughout.
---
/cc @technoweenie @andyneff

all: bootstrap using `release-1.5` tree

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
debian_7.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile

This pull request resolves the other component of https://github.com/git-lfs/git-lfs/issues/2141 and builds all Git LFS Linux packages on Go 1.8.1.
---

all: build using Go 1.8.1

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
commit_tags.bsh
debian_7.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile

This pull request upgrades our Docker images to build using Go 1.8.3. For more discussion, see: https://github.com/git-lfs/git-lfs/pull/2262.
While I was upgrading, I noticed that our commit_tags script bootstraps using an old version of LFS and Go, so I upgraded both to the latest to match.
---

all: build against Go 1.8.3

---

centos_6.Dockerfile
centos_7.Dockerfile

This pull request builds Git LFS on Centos 6, and Centos 7 using the latest MINOR version of Git, v2.16.0. This is necessary in order to support additional functionality added in Git LFS v2.4.0
##

centos: install latest version of Git

---

build_dockers.bsh
push_docker.bsh

In [1], Git LFS began using packages from Docker Hub [2] to bootstrap
platform-specific '*.deb' and '*.rpm' packages using the 'gitlfs'
organization handle.
When building and pushing Docker images, let's use the same name. This
has the benefit of again allowing us to build Docker images locally that
are used by Git LFS, such that a release maintainer can build packages
themselves.
This flow does not require the user to invoke Docker Hub (or have a
network connection, save for getting the latest upstream debian or
centos images) and allows for a fast feedback loop when developing.
##
/cc @git-lfs/core 
[1]: git-lfs@b15ca36f (run against gitlfs packages from docker hub,
2016-08-02)
[2]: https://hub.docker.com

{build,push}_docker.bsh: use up-to-date image name

---

test_lfs.bsh

In [1] and [2], Git LFS learned how to run its tests under prove(1) and
replaced many of its script/*'s with Makefile-based targets.
The platform-specific instructions for building `*.deb`'s and `*.rpm`'s
must update accordingly so as not to refer to outdated (and now broken
invocations) such as script/test. For example, this particular
invocation--script/test--should be replaced with 'make test' instead.
Apply the necessary changes to avoid bitrot and keep the Git LFS
script/target invocations up-to-date.
##
/cc @git-lfs/core 
[1]: https://github.com/git-lfs/git-lfs/pull/3125
[2]: https://github.com/git-lfs/git-lfs/pull/3144

test_lfs.bsh: replace script invocations with make targets

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
centos_script.bsh
commit_tags.bsh
debian_7.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile
debian_script.bsh

Because of a change in Go's package go/ast, the gofmt tool formats
certain whitespace changes differently between versions Go 1.10 and Go
1.11. To resolve this ambiguity in versions, let's upgrade Git LFS to
built on Go 1.11, after having waited several weeks since its release.
In order to release another version in the v2.5.x-series, a release
manager must ensure that they are using the non-Go 1.11 images (i.e.,
42a794c (Merge pull request #22 from git-lfs/ttaylorr/go-1.10.3,
2018-07-25) or earlier).
##

all: build against Go 1.11

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
commit_tags.bsh
debian_7.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile

Per [1], let's make sure that the packages we are building ourselves for
Linux are up-to-date with the version of Go that we are testing in CI.
[1]: git-lfs/git-lfs@88bc4c7f (all: use Go 1.11.1 in CI, 2018-10-02)
##

all: build on Go 1.11.1

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
commit_tags.bsh
debian_10.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile

This will bump the latest go security patch for 1.12. I wasn't sure if this should go directly to 1.13

Update Go version to 1.13.1

---

centos_8.Dockerfile

CentOS 8 is now released and has Docker images, so build a Docker image for it.

Add a Dockerfile for CentOS 8

---

centos_6.Dockerfile
centos_7.Dockerfile

We build with the Docker containers primarily on Actions these days, where the containers are created new each time.  Building Git LFS during the setup stage means that we must run the entire build and testsuite for a container which will only be used once, which is very expensive.
Remove the code which builds during the setup stage of the Docker containers to make the process faster.

centos: don't build Git LFS during setup

---

build_dockers.bsh
centos_6.Dockerfile
centos_7.Dockerfile
centos_8.Dockerfile
debian_10.Dockerfile
debian_8.Dockerfile
debian_9.Dockerfile

Right now, we download archives from the Internet into our container and then essentially execute their code.  While the downloads happen over HTTPS, this isn't the greatest idea from a security perspective, especially if we're then using the result to build software we're distributing.
This series adds some changes to the Dockerfiles and scripts to check the hashes of the archives we download.  The hashes provided either come from the Go release page or the signed archives provided by the kernel.org autosigner, as appropriate.
I've tested that the entire Git LFS package build process completes after running building Docker containers using this series.

Check hashes of downloaded archives

---

build_dockers.bsh
build_one

Currently, building our Docker containers sequentially takes about 14 minutes from a fresh image on a reasonably fast connection.  This expense must be incurred every time we run a new CI job.
To counter this, let's teach build_dockers.bsh a command to run things in parallel using GNU parallel.  The command works very similarly to xargs, and we can continue to default to running things in serial if the user doesn't specify the -j option. In order to make this possible, move the actual build process for a single image into a separate script so it's easy to run from parallel.
Note that before this change, the job took 14 minutes on a MacBook Pro 2018 running Linux; afterwards, it takes 6.  The improvements in CI will be less noticeable since we have fewer processors, but should still be …

build_dockers: add a -j option to parallelize

---

build_dockers.bsh
centos_7.Dockerfile
centos_8.Dockerfile
debian_10.Dockerfile
debian_9.Dockerfile

Update to the latest version of Go, 1.16.2.

Update to Go 1.16.2

---

debian_11.Dockerfile

In CI, we build our Debian packages with cgo enabled.  In order to do so successfully, we need a compiler for i686 and the shared libraries from the Debian i386 architecture in order so that dpkg-shlibdeps can specify the proper dependencies.  Let's install these packages in order to make it possible to build our i386 packages in the same container as amd64.

debian: install packages for building with cgo on i686

---

centos_8.Dockerfile

At the end of 2021, CentOS 8 is going EOL.  Let's switch to Rocky Linux, which is the similarly based around a rebuild of RHEL 8.  We keep the "centos_8" name because it avoids a lot of needless changes to various repositories.
Closes git-lfs/git-lfs#4680

Switch to Rocky Linux

---

debian_10.Dockerfile
debian_11.Dockerfile
debian_9.Dockerfile

In the future, we'll need gettext for building Debian packages.  Let's make sure to include it in our containers.

debian: include gettext

---

rocky_9.Dockerfile

Now that RHEL 9 is out, let's perform a RHEL 9-equivalent build.  Use Rocky Linux 9 for this purpose, since it's a rebuild of RHEL 9 and doesn't require payment for a license.

Add a Dockerfile for Rocky Linux 9

---

build_dockers.bsh
centos_7.Dockerfile
centos_8.Dockerfile
debian_10.Dockerfile
debian_11.Dockerfile
debian_9.Dockerfile
rocky_9.Dockerfile

We want to update to the latest version of Go to get performance and security fixes.  Let's use the `update-hashes` script to update to Go 1.19.3.

Bump Go version to 1.19.3

---

README.md
build_dockers.bsh
build_one
commit_tags.bsh

In commit 330be9d601b234dbc75b4fe68c3a76fd4a7d49e2 of PR #30 we removed the directives from the CentOS Dockerfiles which compiled a version of Git LFS using a stable release version during the container image setup/build stage, as was originally done to save compilation time later when the containers were run.  This was no longer valuable as it increased the overall runtime in GitHub Actions, where we build containers but only use them once, so we removed the directives.
However, we did not remove the supporting references to the `DOCKER_LFS_BUILD_VERSION` environment variable which could be used to set the specific version of the "bootstrapped" Git LFS build, so we remove them now along with the relevant documentation.

Remove `DOCKER_LFS_BUILD_VERSION` environment variable and documentation

---

LICENSE.md
README.md
SECURITY.md
trigger.bsh

We rename references to our primary trunk branch to `main` in the expectation that we will rename the branch in the repository before or immediately after merging this commit's PR.
We also add a security policy document which simply references our primary security policy in the `git-lfs/git-lfs` repository, and an MIT license file which matches those of our other projects.

Rename default branch name to `main` in references and add security and license documentation

---

centos_7.Dockerfile
centos_8.Dockerfile
debian_10.Dockerfile
debian_11.Dockerfile
debian_12.Dockerfile
rocky_9.Dockerfile

Since commit 99652c393fcbd8b3b1da33eacd7230da8d00cc4f in PR #31 our Dockerfiles verify the SHA-256 hash of the Go release package they download and then use to build Git LFS.
As described in git-lfs/git-lfs#5477, we want to avoid any deviation from the use of this verified Go release package, and so before we upgrade to Go 1.21, we need to ensure the new `GOTOOLCHAIN` environment variable is set to `local` before any Go commands are executed. This will prevent the behaviour, added in Go 1.21, whereby Go may download and use a newer version of itself if it detects certain conditions, such as a Go module dependency which requires a newer version of Go than the one installed locally.  While we expect to be able to avoid such conditions in general, defining `GOTOOLCHAIN=local` will guarantee …

*.Dockerfile: force use of local Go toolchain

---

build_dockers.bsh

fix: wrong parameter comments in build scripts

fix: wrong parameter comments in build scripts

---

rocky_9.Dockerfile

Yum is on its way out and has been mostly replaced by DNF.  The former is no longer installed by default on Rocky images, so let's switch to the latter to keep things working.

Rocky 9: use `dnf` instead of `yum`

---

centos_7.Dockerfile

CentOS 7 reached its EOL in June 2024, and so the `mirror.centos.org` and `mirrorlist.centos.org` domains no longer resolve, which means our `build-docker` CI [job](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/.github/workflows/ci.yml#L176-L188) in the main `git-lfs/git-lfs` project is now [failing](https://github.com/git-lfs/git-lfs/actions/runs/9747225509/job/26916598517).
As we hope to be able to [provide](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/script/lib/distro.rb#L38) Git LFS release packages for SUSE Linux Enterprise Server 12.5 until its long-term support ends in October 2027, or at least until its regular support ends in October 2024, we want to continue building Docker images with CentOS 7 if possible …

Install from `vault.centos.org` for CentOS 7

---

build_dockers.bsh
centos_7.Dockerfile
centos_8.Dockerfile
debian_10.Dockerfile
debian_11.Dockerfile
debian_12.Dockerfile
rocky_9.Dockerfile

Using our `update-hashes` script we upgrade our Docker builds to the same version of Go currently used by our main project's CI suite, which is Go version 1.23.3.

Upgrade Go to 1.23.3
